<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAjhX4vp\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAjhX4vp/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAjhX4vp.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAjhX4vp\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerAjhX4vp\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'AjhX4vp',
    'container.build_id' => 'a21c72c4',
    'container.build_time' => 1525676059,
));
